# Generated by Django 4.2.6 on 2023-10-09 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myCards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cards',
            name='amount',
            field=models.IntegerField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cards',
            name='card_pin',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='cards',
            name='card_type',
            field=models.CharField(choices=[('Apple', 'Apple'), ('Amazon', 'Amazon'), ('Steam', 'Steam'), ('eBay', 'eBay'), ('Xbox', 'Xbox'), ('Googleplay', 'Googleplay'), ('PlayStation', 'PlayStation'), ('Sephora', 'Sephora'), ('RazerGold', 'RazerGold'), ('Nordstrom', 'Nordstrom'), ('Nike', 'Nike'), ('MasterCard', 'MasterCard'), ('Vanilla_Visa', 'Vanilla Visa'), ('Wallmart_Visa', 'Wallmart Visa'), ('Visa_Slivery_White', 'Visa Slivery White'), ('TT_Visa', 'TT Visa'), ('Amex', 'Amex')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cards',
            name='code',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cards',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD'), ('GBP', 'GBP'), ('AUD', 'AUD'), ('EUR', 'EUR'), ('CAD', 'CAD')], default=1, max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cards',
            name='cvv',
            field=models.IntegerField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='cards',
            name='exp_date',
            field=models.DateField(blank=True, max_length=10, null=True),
        ),
    ]
