# Generated by Django 4.2.6 on 2023-10-09 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myCards', '0002_cards_amount_cards_card_pin_cards_card_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cards',
            name='exp_date',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
