# Generated by Django 4.2.6 on 2023-10-09 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myCards', '0003_alter_cards_exp_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cards',
            name='card_type',
            field=models.CharField(choices=[('Apple', 'Apple'), ('Amazon', 'Amazon'), ('Steam', 'Steam'), ('eBay', 'eBay'), ('Xbox', 'Xbox'), ('Googleplay', 'Googleplay'), ('PlayStation', 'PlayStation'), ('Sephora', 'Sephora'), ('RazerGold', 'RazerGold'), ('Nordstrom', 'Nordstrom'), ('Nike', 'Nike'), ('MasterCard', 'MasterCard'), ('Vanilla', 'Vanilla Visa'), ('Wallmart Visa', 'Wallmart Visa'), ('Visa Slivery White', 'Visa Slivery White'), ('TT Visa', 'TT Visa'), ('Amex', 'Amex')], max_length=50),
        ),
    ]
